//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using AssemblyCSharp;
using UnityEngine;
using System.Collections;


namespace AssemblyCSharp
{
    public class Cell : MonoBehaviour
    {
        public int PlayerID;
        public int SoldierID;
        public GameObject Soldier;
        public GameObject CellTexture;
        public Vector2 Position;

        public Cell(Vector2 position, GameObject cellTexture)
        {
            PlayerID = 0;
            SoldierID = 0;
            Soldier = new GameObject();
            Position = position;
            CellTexture = cellTexture;
        }
        public void SetSoldier(int soldierID, int PlayerID, GameObject _soldier)
        {
            Soldier = _soldier;
        }

    }
}

