//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using AssemblyCSharp;
using UnityEngine;
using System.Collections;


namespace AssemblyCSharp
{
    public class Field : MonoBehaviour
    {
        public struct Soldier { public GameObject SoldierModel; public int PlayerID;}

        GameObject cellTexture;
        public Soldier[] soldiers;
        public Cell[,] field;

        public void CreateField(int size)
        {
            field = new Cell[size - 2, size];

            for (int y = 0; y < size; y++)
            {
                for (int x = 0; x < size - 2; x++)
                {
                    field[x, y] = new Cell(new Vector2(x, y), cellTexture);
                    Instantiate(field[x, y].CellTexture, new Vector3(419 + x * 25, 1, 145 + y * 25), Quaternion.identity);
                }
            }
        }
        public Field(GameObject CellTexture)
        {
            cellTexture = CellTexture;
        }

    }
}

